version: '3'

services:
  node0:
    container_name: bfhevmnode0
    image: "bfhevm/node"
    ports:
      - "26651:26657"
      - "8541:8545"
      - "8551:8546"
      - "1311:1317"
      - "9050:9090"
      - "26611:26656"
    environment:
      - ID=0
      - LOG=${LOG:-bfhevmd.log}
    volumes:
      - ./localnet-setup/node0/bfhevmd:/bfhevm:Z
    networks:
      - localnet
    entrypoint: "bash $HOME/bfhevm/start-docker.sh"

  node1:
    container_name: bfhevmnode1
    image: "bfhevm/node"
    ports:
      - "26652:26657"
      - "8542:8545"
      - "8552:8546"
      - "1312:1317"
      - "9060:9090"
      - "26612:26656"
    environment:
      - ID=0
      - LOG=${LOG:-bfhevmd.log}
    volumes:
      - ./localnet-setup/node1/bfhevmd:/bfhevm:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  node2:
    container_name: bfhevmnode2
    image: "bfhevm/node"
    ports:
      - "26653:26657"
      - "8543:8545"
      - "8553:8546"
      - "1313:1317"
      - "9070:9090"
      - "26613:26656"
    environment:
      - ID=0
      - LOG=${LOG:-bfhevmd.log}
    volumes:
      - ./localnet-setup/node2/bfhevmd:/bfhevm:Z
    networks:
      - localnet
    entrypoint: "bash $HOME/bfhevm/start-docker.sh"


    node3:
    container_name: bfhevmnode3
    image: "bfhevm/node"
    ports:
      - "26654:26657"
      - "8544:8545"
      - "8554:8546"
      - "1314:1317"
      - "9080:9090"
      - "26614:26656"
    environment:
      - ID=0
      - LOG=${LOG:-bfhevmd.log}
    volumes:
      - ./localnet-setup/node3/bfhevmd:/bfhevm:Z
    networks:
      - localnet
    entrypoint: "bash $HOME/bfhevm/start-docker.sh"

networks:
  localnet:

